spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wipropractise1
    username: root
    password: Siddu@123456789
  jpa:
    hibernate.ddl-auto: update
    show-sql: true